<a href="https://colab.research.google.com/github/123akanksha-ak/Google_cloud_skill_2024/blob/master/Movie_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:

print("MOVIE RECOMMENDATION SYSTEM")
print("Welcome to our Data Science Project")

MOVIE RECOMMENDATION SYSTEM
Welcome to our Data Science Project

In [47]:

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("Libraries imported successfully!")

Libraries imported successfully!

In [48]:

data = {
    "title": [
        "3 Idiots",
        "Chhichhore",
        "Dangal",
        "Taare Zameen Par",
        "Zindagi Na Milegi Dobara",
        "Dil Chahta Hai",
        "War",
        "Pathaan",
        "PK",
        "Munna Bhai M.B.B.S."
    ],

    "genre": [
        "comedy drama education",
        "comedy drama college",
        "sports drama",
        "drama education family",
        "adventure comedy drama",
        "friendship comedy drama",
        "action thriller",
        "action thriller",
        "comedy drama science fiction",
        "comedy drama medical"
    ],

    "rating": [
        8.4, 8.3, 8.3, 8.4, 8.2,
        8.1, 6.5, 5.8, 8.1, 8.1
    ]
}

movies = pd.DataFrame(data)

print(movies)

                      title                         genre  rating
0                  3 Idiots        comedy drama education     8.4
1                Chhichhore          comedy drama college     8.3
2                    Dangal                  sports drama     8.3
3          Taare Zameen Par        drama education family     8.4
4  Zindagi Na Milegi Dobara        adventure comedy drama     8.2
5            Dil Chahta Hai       friendship comedy drama     8.1
6                       War               action thriller     6.5
7                   Pathaan               action thriller     5.8
8                        PK  comedy drama science fiction     8.1
9       Munna Bhai M.B.B.S.          comedy drama medical     8.1

In [49]:

print("Total movies:", len(movies))

print("\nMovie Dataset:")
display(movies)

print("\nAverage Rating:")
print(round(movies["rating"].mean(), 2))

Total movies: 10

Movie Dataset:

                      title                         genre  rating
0                  3 Idiots        comedy drama education     8.4
1                Chhichhore          comedy drama college     8.3
2                    Dangal                  sports drama     8.3
3          Taare Zameen Par        drama education family     8.4
4  Zindagi Na Milegi Dobara        adventure comedy drama     8.2
5            Dil Chahta Hai       friendship comedy drama     8.1
6                       War               action thriller     6.5
7                   Pathaan               action thriller     5.8
8                        PK  comedy drama science fiction     8.1
9       Munna Bhai M.B.B.S.          comedy drama medical     8.1

Average Rating:
7.82

In [50]:

popular_movies = movies.sort_values(
    by="rating",
    ascending=False
)

print("Top 5 Movies:")
display(popular_movies[["title", "rating"]].head(5))

Top 5 Movies:

                      title  rating
0                  3 Idiots     8.4
3          Taare Zameen Par     8.4
1                Chhichhore     8.3
2                    Dangal     8.3
4  Zindagi Na Milegi Dobara     8.2

In [51]:

vectorizer = TfidfVectorizer()

genre_matrix = vectorizer.fit_transform(
    movies["genre"]
)

print("Genre processing completed!")
print("Matrix shape:", genre_matrix.shape)

Genre processing completed!
Matrix shape: (10, 13)

In [52]:

similarity_matrix = cosine_similarity(genre_matrix)

print("Similarity calculation completed!")
print("Matrix shape:", similarity_matrix.shape)

Similarity calculation completed!
Matrix shape: (10, 10)

In [53]:

def recommend_movies(movie_name, n=3):

    matches = movies.index[
        movies["title"].str.lower() == movie_name.lower()
    ].tolist()

    if not matches:
        print("Movie not found! Please enter a valid title.")
        return

    movie_index = matches[0]

    scores = list(enumerate(
        similarity_matrix[movie_index]
    ))

    scores = sorted(
        scores,
        key=lambda item: item[1],
        reverse=True
    )

    recommendations = [
        item for item in scores
        if item[0] != movie_index
    ][:n]

    print("Movies similar to", movie_name)

    for index, score in recommendations:
        print(
            movies.iloc[index]["title"],
            "| Similarity:",
            round(score, 2)
        )

In [54]:

recommend_movies("Dangal")
recommend_movies("War")
recommend_movies("PK")

Movies similar to Dangal
3 Idiots | Similarity: 0.16
Chhichhore | Similarity: 0.15
Zindagi Na Milegi Dobara | Similarity: 0.15
Movies similar to War
Pathaan | Similarity: 1.0
3 Idiots | Similarity: 0.0
Chhichhore | Similarity: 0.0
Movies similar to PK
3 Idiots | Similarity: 0.28
Chhichhore | Similarity: 0.25
Zindagi Na Milegi Dobara | Similarity: 0.25